# Generated by Django 5.2.12 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=100)),
                ('student_address', models.TextField()),
            ],
        ),
    ]
