# Generated by Django 5.2.12 on 2026-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
